name = "SearchingTales"
uuid = "a6a8f54e-74dd-4b1c-96c8-6661afa4740d"
authors = ["Laura Brustenga i Moncusí <brust@math.ku.dk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
